# Generated by Django 4.0.3 on 2022-03-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacherprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
