# Generated by Django 4.0.3 on 2022-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/'),
        ),
    ]
