# Generated by Django 4.0.3 on 2022-03-05 02:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=200)),
                ('syllabus', models.TextField()),
                ('subjectCode', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classData',
            fields=[
                ('programme', models.CharField(blank=True, choices=[('Computer Engineering', 'BCT'), ('Electrical Engineering', 'BEL'), ('Electronic and Communication Engineering', 'BEX')], max_length=200)),
                ('year', models.CharField(blank=True, choices=[('I', 'FIRST'), ('II', 'SECOND'), ('III', 'THIRD'), ('IV', 'FOURTH')], max_length=200)),
                ('part', models.CharField(blank=True, choices=[('I', 'FIRST'), ('II', 'SECOND')], max_length=200)),
                ('batch', models.CharField(blank=True, max_length=200)),
                ('group', models.CharField(choices=[('AB', 'AB'), ('CD', 'CD')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subjects', models.ManyToManyField(blank=True, to='classes.subject')),
            ],
        ),
    ]
