# Generated by Django 4.0.3 on 2022-03-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmarks',
            name='passMarks',
            field=models.IntegerField(null=True),
        ),
    ]
