# Generated by Django 4.0.3 on 2022-03-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_teacher_profile_pic'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMarks',
            fields=[
                ('getClass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.classdata')),
                ('fullMarks', models.IntegerField()),
                ('type', models.CharField(choices=[('theory', 'th'), ('practical', 'Prac')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=3, null=True)),
                ('Dept', models.CharField(max_length=3, null=True)),
                ('Roll', models.CharField(max_length=3, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='subjects',
        ),
        migrations.AddField(
            model_name='classdata',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classdata',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classdata',
            name='subjectAlias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classdata',
            name='subjectName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classdata',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classdata',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='classdata',
            name='group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200),
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
