# Generated by Django 4.0.3 on 2022-03-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_studentdata_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdata',
            old_name='programme',
            new_name='dept',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='created',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='subjectAlias',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='subjectName',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='syllabus',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='teacher',
        ),
    ]
