# Generated by Django 4.0.3 on 2022-03-09 08:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teacher_profile_pic'),
        ('classes', '0005_rename_programme_classdata_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmarks',
            name='Marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, null=True), max_length=24, null=True, size=None),
        ),
        migrations.AddField(
            model_name='assessmentmarks',
            name='Subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assessmentmarks',
            name='Teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.teacher'),
        ),
    ]
