# Generated by Django 4.0.3 on 2022-03-09 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_assessmentmarks_marks_assessmentmarks_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmarks',
            name='Marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, null=True), null=True, size=24),
        ),
    ]
