# Generated by Django 4.0.3 on 2022-03-09 09:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_assessmentmarks_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmarks',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentmarks',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='Marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2, null=True), blank=True, null=True, size=24),
        ),
    ]
