# Generated by Django 4.0.3 on 2022-03-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teacher_profile_pic'),
        ('classes', '0009_alter_classdata_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmarks',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='getClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classes.classdata'),
        ),
    ]
