# Generated by Django 4.0.3 on 2022-03-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_teacher_profile_pic'),
        ('classes', '0010_alter_assessmentmarks_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmarks',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='assessmentmarks',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='classdata',
            name='subjectName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classdata',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='getClass',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='classes.classdata'),
        ),
    ]
