# Generated by Django 4.0.3 on 2022-03-09 10:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_remove_assessmentmarks_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmarks',
            name='Marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, null=True), blank=True, null=True, size=24),
        ),
    ]
