# Generated by Django 4.0.3 on 2022-03-09 17:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_assessmentmarks_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmarks',
            name='Marks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=[1, 2, 3], null=True, size=24),
        ),
    ]
