# Generated by Django 4.0.3 on 2022-03-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_remove_assessmentmarks_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks11',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks12',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks13',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks14',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks15',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks16',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks17',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks18',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks19',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks21',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks22',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks23',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks24',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks6',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks7',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks8',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks9',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
