# Generated by Django 4.0.3 on 2022-03-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_assessmentmarks_submittedmarks1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks17',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks18',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks19',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks20',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks21',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks22',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks23',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks24',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='SubmittedMarks9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentmarks',
            name='fullMarks',
            field=models.IntegerField(null=True),
        ),
    ]
